apiVersion: v1
name: servarr
version: "1.0.15"
kubeVersion: ">=1.23.0-0"
description: Helm Chart for all servarr apps, such as lidarr, radarr, readarr, sonarr, whisparr 
appVersion: "v3"
home: https://github.com/wattos/home-lab-charts
maintainers:
- email: wattos@users.noreply.github.com
  name: wattos
sources:
- https://github.com/wattos/home-lab-charts
