apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
  replicas: {{ default 1 .Values.servarr.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers: {{ $app := (index .Values .Values.app) }}
      - name: "{{ .Values.app }}"
        image: "{{ $app.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ $app.container.port | int }}
        env:
        - name: PGID
          value: "{{ .Values.servarr.uid }}"
        - name: PUID
          value: "{{ .Values.servarr.gid }}"
        - name: TZ
          value: "{{ .Values.servarr.timezone }}"
        volumeMounts:
        - name: "{{ .Values.app }}-config"
          mountPath: /config
        {{- if $app.media.enabled }}
        - name: "{{ .Values.app }}-media"
          mountPath: /media
        {{- end }}
      volumes:
      - name: "{{ .Values.app }}-config"
        persistentVolumeClaim:
          claimName: "{{ .Values.app }}-config"
      {{- if $app.media.enabled }}
      - name: "{{ .Values.app }}-media"
        nfs:
          server: "{{ .Values.servarr.media.volume.nfs.server }}"
          path: "{{ .Values.servarr.media.volume.nfs.path }}"
      {{- end }}