{{- $app := (index .Values .Values.app) -}}
{{- $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: {{ .Values.app }} 
    port: 80
    targetPort: {{ $app.container.port }}
    
  selector:
    app: {{ $fullname }}