{{- $app := (index .Values .Values.app) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: {{ .Values.app }} 
    port: 80
    targetPort: {{ $app.container.port }}
    
  selector:
    app: {{ .Values.app }}