apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.servarr.config.storage.className }}"
  resources:
    requests:
      storage: "{{ .Values.servarr.config.storage.size }}"