deployment:
  enabled: true
  image: "lscr.io/linuxserver/emby:latest"
  port: 8096
  replicaCount: 1
  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: CET

ingress:
  enabled: true
  annotations: {}
  host:

service:
  enabled: true

storage:
  mounts:
    config:
      enabled: true
      storageClassName:
      size: 50000Mi

    media:
      enabled: true
      volume:
        nfs:
          path:
          server:
    
    videoDriver:
      enabled: true
      path:
  
